#!/bin/sh
# Skip commitlint for semantic-release commits
if grep -q "^chore(release):" "$1"; then
  echo "Skipping commitlint for semantic-release commit"
  exit 0
fi

# Otherwise, run commitlint as usual
npm run commitlint ${1}